name: Shared .NET CI with SonarCloud

on:
    workflow_call:
        inputs:
            dotnet-version:
                description: "The .NET SDK version"
                required: false
                type: string
                default: "10.0.x"
            sonar-project-key:
                description: "The unique project key on SonarCloud"
                required: true
                type: string
        secrets:
            SONAR_TOKEN:
                required: true
            SONAR_ORGANIZATION_KEY:
                required: true

jobs:
    build:
        name: Build & Test .NET
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: ${{ inputs.dotnet-version }}

            - name: Setup Java 17 (Required by SonarScanner)
              uses: actions/setup-java@v5
              with:
                  java-version: "17"
                  distribution: "zulu"

            - name: Install SonarScanner
              run: dotnet tool install --global dotnet-sonarscanner

            - name: Restore dependencies
              run: dotnet restore

            - name: Start SonarCloud analysis
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: >
                  dotnet sonarscanner begin
                  /k:"${{ inputs.sonar-project-key }}"
                  /o:"${{ secrets.SONAR_ORGANIZATION_KEY }}"
                  /d:sonar.host.url="https://sonarcloud.io"
                  /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
                  /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
                  /d:sonar.qualitygate.wait=true

            - name: Build
              run: dotnet build --no-restore --configuration Release

            - name: Unit Tests and Code Coverage
              run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

            - name: Finalize SonarCloud analysis
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
